<font face='georgia'>
    
   <h4><strong>What does tf-idf mean?</strong></h4>

   <p>    
Tf-idf stands for <em>term frequency-inverse document frequency</em>, and the tf-idf weight is a weight often used in information retrieval and text mining. This weight is a statistical measure used to evaluate how important a word is to a document in a collection or corpus. The importance increases proportionally to the number of times a word appears in the document but is offset by the frequency of the word in the corpus. Variations of the tf-idf weighting scheme are often used by search engines as a central tool in scoring and ranking a document's relevance given a user query.
</p>
    
   <p>
One of the simplest ranking functions is computed by summing the tf-idf for each query term; many more sophisticated ranking functions are variants of this simple model.
</p>
    
   <p>
Tf-idf can be successfully used for stop-words filtering in various subject fields including text summarization and classification.
</p>
    
</font>

<font face='georgia'>
    <h4><strong>How to Compute:</strong></h4>

Typically, the tf-idf weight is composed by two terms: the first computes the normalized Term Frequency (TF), aka. the number of times a word appears in a document, divided by the total number of words in that document; the second term is the Inverse Document Frequency (IDF), computed as the logarithm of the number of the documents in the corpus divided by the number of documents where the specific term appears.

 <ul>
    <li>
<strong>TF:</strong> Term Frequency, which measures how frequently a term occurs in a document. Since every document is different in length, it is possible that a term would appear much more times in long documents than shorter ones. Thus, the term frequency is often divided by the document length (aka. the total number of terms in the document) as a way of normalization: <br>

$TF(t) = \frac{\text{Number of times term t appears in a document}}{\text{Total number of terms in the document}}.$
</li>
<li>
<strong>IDF:</strong> Inverse Document Frequency, which measures how important a term is. While computing TF, all terms are considered equally important. However it is known that certain terms, such as "is", "of", and "that", may appear a lot of times but have little importance. Thus we need to weigh down the frequent terms while scale up the rare ones, by computing the following: <br>

$IDF(t) = \log_{e}\frac{\text{Total  number of documents}} {\text{Number of documents with term t in it}}.$
for numerical stabiltiy we will be changing this formula little bit
$IDF(t) = \log_{e}\frac{\text{Total  number of documents}} {\text{Number of documents with term t in it}+1}.$
</li>
</ul>

<br>
<h4><strong>Example</strong></h4>
<p>

Consider a document containing 100 words wherein the word cat appears 3 times. The term frequency (i.e., tf) for cat is then (3 / 100) = 0.03. Now, assume we have 10 million documents and the word cat appears in one thousand of these. Then, the inverse document frequency (i.e., idf) is calculated as log(10,000,000 / 1,000) = 4. Thus, the Tf-idf weight is the product of these quantities: 0.03 * 4 = 0.12.
</p>
</font>

## Task-1

<font face='georgia'>
    <h4><strong>1. Build a TFIDF Vectorizer & compare its results with Sklearn:</strong></h4>

<ul>
    <li> As a part of this task you will be implementing TFIDF vectorizer on a collection of text documents.</li>
    <br>
    <li> You should compare the results of your own implementation of TFIDF vectorizer with that of sklearns implemenation TFIDF vectorizer.</li>
    <br>
    <li> Sklearn does few more tweaks in the implementation of its version of TFIDF vectorizer, so to replicate the exact results you would need to add following things to your custom implementation of tfidf vectorizer:
       <ol>
        <li> Sklearn has its vocabulary generated from idf sroted in alphabetical order</li>
        <li> Sklearn formula of idf is different from the standard textbook formula. Here the constant <strong>"1"</strong> is added to the numerator and denominator of the idf as if an extra document was seen containing every term in the collection exactly once, which prevents zero divisions.
            
 $IDF(t) = 1+\log_{e}\frac{1\text{ }+\text{ Total  number of documents in collection}} {1+\text{Number of documents with term t in it}}.$
        </li>
        <li> Sklearn applies L2-normalization on its output matrix.</li>
        <li> The final output of sklearn tfidf vectorizer is a sparse matrix.</li>
    </ol>
    <br>
    <li>Steps to approach this task:
    <ol>
        <li> You would have to write both fit and transform methods for your custom implementation of tfidf vectorizer.</li>
        <li> Print out the alphabetically sorted voacb after you fit your data and check if its the same as that of the feature names from sklearn tfidf vectorizer. </li>
        <li> Print out the idf values from your implementation and check if its the same as that of sklearns tfidf vectorizer idf values. </li>
        <li> Once you get your voacb and idf values to be same as that of sklearns implementation of tfidf vectorizer, proceed to the below steps. </li>
        <li> Make sure the output of your implementation is a sparse matrix. Before generating the final output, you need to normalize your sparse matrix using L2 normalization. You can refer to this link https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.normalize.html </li>
        <li> After completing the above steps, print the output of your custom implementation and compare it with sklearns implementation of tfidf vectorizer.</li>
        <li> To check the output of a single document in your collection of documents,  you can convert the sparse matrix related only to that document into dense matrix and print it.</li>
        </ol>
    </li>
    <br>
   </ul>

  <p> <font color="#e60000"><strong>Note-1: </strong></font> All the necessary outputs of sklearns tfidf vectorizer have been provided as reference in this notebook, you can compare your outputs as mentioned in the above steps, with these outputs.<br>
   <font color="#e60000"><strong>Note-2: </strong></font> The output of your custom implementation and that of sklearns implementation would match only with the collection of document strings provided to you as reference in this notebook. It would not match for strings that contain capital letters or punctuations, etc, because sklearn version of tfidf vectorizer deals with such strings in a different way. To know further details about how sklearn tfidf vectorizer works with such string, you can always refer to its official documentation.<br>
   <font color="#e60000"><strong>Note-3: </strong></font> During this task, it would be helpful for you to debug the code you write with print statements wherever necessary. But when you are finally submitting the assignment, make sure your code is readable and try not to print things which are not part of this task.
    </p>

In [12]:
from collections import Counter
from tqdm import tqdm
from scipy.sparse import csr_matrix
import math
import operator
from sklearn.preprocessing import normalize
import numpy

corpus = [
     'this is the first document',
     'this document is the second document',
     'and this is the third one',
     'is this the first document',
]

import numpy as np
import operator


def fit(dataset):   
    
    unique_words_list = set()# unique words in a corpus
    freq_dict = {}#Total number of documents containing a given word
    doc_count = 0
    idf_list = []
    
    # check if its list type or not
    if isinstance(dataset, (list,)):
        
        # for each review in the dataset
        for row in dataset:
            unique_words_in_a_doc_list = set()#unique words in a dcument
            doc_count += 1
            
            #taking into account each word in a row/document and populating our unique_words_in_a_doc_list and 
            #unique_words_list lists'
            for word in row.split(" "): 
                if len(word) < 2:
                    continue
                unique_words_in_a_doc_list.add(word)
                unique_words_list.add(word)
            
            #forming the freq_dict dictionary
            for word in unique_words_in_a_doc_list:
                if word in freq_dict.keys():
                    freq_dict[word] = freq_dict.get(word) + 1
                else:
                    freq_dict[word] = 1
        unique_words_list = sorted(list(unique_words_list))
        freq_dict = sorted(freq_dict.items()) 
        
        #calculating idf values for each word in the freq_dict and storing it in idf_list
        for item in freq_dict:
            values = operator.add(1,np.log(operator.truediv(operator.add(1,doc_count),operator.add(1,item[1]))))
            idf_list.append(values)
    
        idf_dict = dict(zip(unique_words_list, idf_list))
        print(idf_dict)
        
        return idf_dict
    else:
        print("you need to pass list of sentance")
        
    

In [13]:
def transform(dataset):
    
    rows = []
    columns = []
    values = []
    idf = fit(dataset)
    vocab = {j:i for i,j in enumerate(idf.keys())}
    
    if isinstance(corpus, (list,)):
        for idx, row in enumerate(tqdm(dataset)):            # for each document in the corpus and a dictionary of the form {word:frequency}
            word_freq = dict(Counter(row.split()))
            for word, freq in word_freq.items():            # for each unique word in the review.                
                if len(word) < 2:
                    continue
                                                            # dict.get() function will return the values, 
                                                            #if the key doesn't exits it will return -1
                col_index = vocab.get(word, -1)             # retreving the dimension number of a word
                                                            # if the word exists
                idf_value=idf.get(word)#IDF value
                tf_idf = (operator.mul(operator.truediv(freq,len(row.split())),idf_value)) #modified TF-IDF value

                
                if col_index !=-1:                          #this is when there is value to be stored as tfidf
                    rows.append(idx)                        # we are to store the row co-ordinates of the word
                    columns.append(col_index)               # we are to store the column co-ordinates of the word
                    values.append(tf_idf)
        return normalize(csr_matrix((values, (rows,columns)), shape=(len(dataset),len(vocab))))
    else:
        print("you need to pass list of strings")

In [14]:
output=transform(corpus)

{'and': 1.916290731874155, 'document': 1.2231435513142097, 'first': 1.5108256237659907, 'is': 1.0, 'one': 1.916290731874155, 'second': 1.916290731874155, 'the': 1.0, 'third': 1.916290731874155, 'this': 1.0}


100%|██████████| 4/4 [00:00<00:00, 1003.12it/s]


In [15]:
output.toarray()

array([[0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
        0.        , 0.38408524, 0.        , 0.38408524],
       [0.        , 0.6876236 , 0.        , 0.28108867, 0.        ,
        0.53864762, 0.28108867, 0.        , 0.28108867],
       [0.51184851, 0.        , 0.        , 0.26710379, 0.51184851,
        0.        , 0.26710379, 0.51184851, 0.26710379],
       [0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
        0.        , 0.38408524, 0.        , 0.38408524]])

## Task 2

<font face='georgia'>
    <h4><strong>2. Implement max features functionality:</strong></h4>

<ul>
    <li> As a part of this task you have to modify your fit and transform functions so that your vocab will contain only 50 terms with top idf scores.</li>
    <br>
    <li>This task is similar to your previous task, just that here your vocabulary is limited to only top 50 features names based on their idf values. Basically your output will have exactly 50 columns and the number of rows will depend on the number of documents you have in your corpus.</li>
    <br>
    <li>Here you will be give a pickle file, with file name <strong>cleaned_strings</strong>. You would have to load the corpus from this file and use it as input to your tfidf vectorizer.</li>
    <br>
    <li>Steps to approach this task:
    <ol>
        <li> You would have to write both fit and transform methods for your custom implementation of tfidf vectorizer, just like in the previous task. Additionally, here you have to limit the number of features generated to 50 as described above.</li>
        <li> Now sort your vocab based in descending order of idf values and print out the words in the sorted voacb after you fit your data. Here you should be getting only 50 terms in your vocab. And make sure to print idf values for each term in your vocab. </li>
        <li> Make sure the output of your implementation is a sparse matrix. Before generating the final output, you need to normalize your sparse matrix using L2 normalization. You can refer to this link https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.normalize.html </li>
        <li> Now check the output of a single document in your collection of documents,  you can convert the sparse matrix related only to that document into dense matrix and print it. And this dense matrix should contain 1 row and 50 columns. </li>
        </ol>
    </li>
    <br>
   </ul>

In [16]:
import pickle
with open('C://Users//jaska//Documents//Applied AI//Applied AI Codes//New folder//cleaned_strings', 'rb') as f:
    corpus = pickle.load(f)
    
# printing the length of the corpus loaded
print("Number of documents in corpus = ",len(corpus))

Number of documents in corpus =  746


In [17]:
def fit(dataset):   
    
    unique_words_list = set() # unique words in a corpus
    freq_dict = {} #Total number of documents containing a given word
    idf_list = [] #list storing idf scores
    doc_count = 0
    
    # check if its list type or not
    if isinstance(dataset, (list,)):
        
        # for each review in the dataset
        for row in dataset:
            
            unique_words_in_a_doc_list = set()#unique words in a d0cument
            doc_count += 1
            
            #taking into account each word in a row/document and populating our  
            #unique_words_in_a_doc_list and unique_words_list lists'
            for word in row.split(" "): 
                if len(word) < 2:
                    continue
                unique_words_in_a_doc_list.add(word)
                unique_words_list.add(word)
            
            #forming the freq_dict dictionary
            for word in unique_words_in_a_doc_list:
                if word in freq_dict.keys():
                    freq_dict[word] = freq_dict.get(word) + 1
                else:
                    freq_dict[word] = 1
                    
        unique_words_list = sorted(list(unique_words_list))
        freq_dict = sorted(freq_dict.items()) 
        
        #calculating idf values for each word in the freq_dict and storing it in idf_list
        for item in freq_dict:
            
            # calculating the idf scores
            values = operator.add(1,np.log(operator.truediv(operator.add(1,doc_count),operator.add(1,item[1]))))
            idf_list.append(values)
        
        # forming idf score dictionary from idf_list
        idf_dict = dict(zip(unique_words_list, idf_list))
        
        #https://stackoverflow.com/a/11902719
        #converting to dict because previously it was returning a list
        idf_dict = dict(sorted(idf_dict.items(), key=lambda x:-x[1])[:50])
        print(len(idf_dict))
                  
        return idf_dict
                  
    else:
        print("you need to pass list of sentance")

In [18]:
fit(corpus) 

50


{'aailiyah': 6.922918004572872,
 'abandoned': 6.922918004572872,
 'abroad': 6.922918004572872,
 'abstruse': 6.922918004572872,
 'academy': 6.922918004572872,
 'accents': 6.922918004572872,
 'accessible': 6.922918004572872,
 'acclaimed': 6.922918004572872,
 'accolades': 6.922918004572872,
 'accurate': 6.922918004572872,
 'accurately': 6.922918004572872,
 'achille': 6.922918004572872,
 'ackerman': 6.922918004572872,
 'actions': 6.922918004572872,
 'adams': 6.922918004572872,
 'add': 6.922918004572872,
 'added': 6.922918004572872,
 'admins': 6.922918004572872,
 'admiration': 6.922918004572872,
 'admitted': 6.922918004572872,
 'adrift': 6.922918004572872,
 'adventure': 6.922918004572872,
 'aesthetically': 6.922918004572872,
 'affected': 6.922918004572872,
 'affleck': 6.922918004572872,
 'afternoon': 6.922918004572872,
 'aged': 6.922918004572872,
 'ages': 6.922918004572872,
 'agree': 6.922918004572872,
 'agreed': 6.922918004572872,
 'aimless': 6.922918004572872,
 'aired': 6.922918004572872,

In [19]:
def transform(dataset):
    
    rows = []
    columns = []
    values = []
    idf = fit(dataset)
    vocab = {j:i for i,j in enumerate(idf.keys())}
    
    if isinstance(corpus, (list,)):
        for idx, row in enumerate(tqdm(dataset)):            # for each document in the corpus and a dictionary of the form {word:frequency}
            word_freq = dict(Counter(row.split()))
            for word, freq in word_freq.items():            # for each unique word in the review.                
                if len(word) < 2:
                    continue
                
                col_index = vocab.get(word, -1) 
                
                if(col_index==-1):
                    continue                                   # dict.get() function will return the values, 
                                                               #if the key doesn't exits it will return -1
                                                                # retreving the dimension number of a word
                                                                # if the word exists
                idf_value=idf.get(word)#IDF value
                tf_idf = (operator.mul(operator.truediv(freq,len(row.split())),idf_value)) #modified TF-IDF value

                
                if col_index !=-1:                          #this is when there is value to be stored as tfidf
                    rows.append(idx)                        # we are to store the row co-ordinates of the word
                    columns.append(col_index)               # we are to store the column co-ordinates of the word
                    values.append(tf_idf)
        return normalize(csr_matrix((values, (rows,columns)), shape=(len(dataset),len(vocab))))
    else:
        print("you need to pass list of strings")

In [21]:
output2=transform(corpus)
output2.shape

50


100%|██████████| 746/746 [00:00<00:00, 83137.18it/s]


(746, 50)

In [11]:
print(output2.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
